function  plot_aerogen_single(states,ctrs, time)
    dt = time(2)-time(1);
    figure
    subplot(2, 2, 1)
    plot(time, states(1, :)/(2*pi))
    title('Sigma')
    xlabel('Time [s]')
    ylabel('Sigma [revs]')
    subplot(2, 2, 2)
    plot(time, states(2, :)/(2*pi))
    title('Sigma dot')
    xlabel('Time [s]')
    ylabel('Sigma dot [rev/s]')
    subplot(2, 2, 3)
    plot(time(1:end-1), ctrs(1, :))
    title('Gen Moment')
    xlabel('Time [s]')
    ylabel('Gen Moment [kNm]')
    subplot(2, 2, 4)
    plot(time(1:end-1), (-ctrs(1, :).*states(2, 1:end-1))/dt)
    title('Objective')
    xlabel('Time [s]')
    ylabel('Power [kW]')

end